import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/contexts/AuthContext";
import MiniKitProvider from "@/components/MiniKitProvider";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunitoSans.variable} dark`}>
      <body className={`${nunitoSans.className} antialiased`}>
        <MiniKitProvider>
          <AuthProvider>
            {children}
            <Toaster position="top-center" richColors />
          </AuthProvider>
        </MiniKitProvider>
      </body>
    </html>
  );
}
